# Generated by Django 5.2 on 2025-04-27 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RecreativeElement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=15)),
                ('capacity', models.IntegerField()),
                ('state', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomXElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecreativeElement.recreativeelement')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.room')),
            ],
            options={
                'unique_together': {('room', 'element')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='recreative_elements',
            field=models.ManyToManyField(related_name='rooms', through='Room.RoomXElements', to='RecreativeElement.recreativeelement'),
        ),
    ]
