# Generated by Django 5.2 on 2025-05-06 02:09

import Room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.JSONField(default=Room.models.defaultAvailability),
        ),
    ]
