# Generated by Django 5.2 on 2025-05-11 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0004_alter_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='state',
        ),
    ]
