# Generated by Django 5.2 on 2025-04-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecreativeElement',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
