# Generated by Django 5.2 on 2025-04-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecreativeElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('quantity', models.IntegerField(db_column='quantity')),
            ],
            options={
                'verbose_name': 'Recreational Item',
                'verbose_name_plural': 'Recreational Items',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='quantity_non_negative')],
            },
        ),
    ]
