# Generated by Django 5.2 on 2025-04-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('registerId', models.AutoField(primary_key=True, serialize=False)),
                ('returnedElements', models.JSONField(default=dict)),
                ('remainingElements', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Registers',
                'ordering': ['reservationId'],
            },
        ),
    ]
