# Generated by Django 5.2 on 2025-05-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
