# Generated by Django 5.2 on 2025-04-27 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RecreativeElement', '0001_initial'),
        ('Reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservationxelements',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecreativeElement.recreativeelement'),
        ),
        migrations.AddField(
            model_name='reservationxelements',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='borrowed_elements',
            field=models.ManyToManyField(blank=True, related_name='reservations', through='Reservation.ReservationXElements', to='RecreativeElement.recreativeelement'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationxelements',
            unique_together={('reservation', 'element')},
        ),
    ]
