# Generated by Django 5.2 on 2025-05-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecreativeElement', '0001_initial'),
        ('Reservation', '0005_remove_reservation_start_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationxelements',
            options={'ordering': ['reservation'], 'verbose_name': 'ReservationXElements', 'verbose_name_plural': 'ReservationsXElements'},
        ),
        migrations.AlterUniqueTogether(
            name='reservationxelements',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='reservationxelements',
            index=models.Index(fields=['reservation'], name='Reservation_reserva_aae514_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationxelements',
            index=models.Index(fields=['element'], name='Reservation_element_44f17b_idx'),
        ),
    ]
